### ISSUE TITLE
Search bar tweak?

### ISSUE THREAD

**Issue by gmemstr** [nicu03/dark-youtube-theme#17]
The blue search button doesn't quite fit in with the rest of the theme, would it be possible to style that?

**Comment by nicu03** [comment]
Hey there!
sure thing. I also have to fix the white background on the search suggestion dropdown.
Thanks!

**Comment by happysurf** [comment]
In my opinion the Search bar have a light gray too strong to the eyes. 
The perfect background color is the same of comments one (#1B1B1B) or something like that.
Thanks.

**Comment by nicu03** [comment]
I updated this a while ago, the search button is grey-ish now
