### ISSUE TITLE
white bar in subscriptions tab

### ISSUE THREAD

**Issue by Them-Ripper** [nicu03/dark-youtube-theme#28]
So i have noticed that there is a white bar in the menu on the subscriptions page. even after reloading and closing the browser
![screenshot_24](https://cloud.githubusercontent.com/assets/11584006/20187112/3583ac60-a773-11e6-85dc-2a3534825fd1.png)

**Comment by nicu03** [comment]
Hey, thanks for reporting this bug. I also saw that white bar but it dissapears after a refresh. Is it still broken for you ?

**Comment by Them-Ripper** [comment]
yes it is still broken even after refreshing and closing the page

**Comment by r15ch13** [comment]
It has something to do with the new bar that asks for desktop notification permission. If you close it or turn it on, there is a margin-top of 85px left behind.

```
.sitewide-ticker-visible #appbar-guide-menu {
    margin-top: 85px;
}
```
Default is: 
```
.appbar-guide-menu-layout {
    margin-top: 50px;
}
```

**Comment by Them-Ripper** [comment]
it got fixed after disabling and reenabling the desktop notification
