### ISSUE TITLE
Can't post a comment on videos

### ISSUE THREAD

**Issue by Nicholas-Steel** [nicu03/dark-youtube-theme#30]
I get a "Comment failed to post" error whenever I try to reply to a comment on a video.

**Comment by nicu03** [comment]
@Nicholas-Steel  hmm .. i just posted a comment with the firefox addon enabled. are you referring to the chrome addon or maybe there's another addon interfering with youtube (like an adblocker) 
thanks for the bug report

**Comment by Nicholas-Steel** [comment]
I guess it is possible that Adblock+ is blocking too much ever since Google messed around with their page design.

Like I just now said in the other report I made, Mozilla Firefox 50.1.0.

**Comment by Nicholas-Steel** [comment]
Well, it's working fine now. So either Adblock+ database got silently updated to fix the issue or Youtube was just having server issues previously.

**Comment by Nicholas-Steel** [comment]
It certainly looks like this is a Youtube bug. Specifically if I click a link on a website which takes me to a specific comment on a video page, when this happens commenting will fail/show an error but if I change the URL and delete everything after the & symbol (lots of superfluous URL stuff) I can comment without issue.

For example: https://www.youtube.com/watch?v=m7wt3F54Oo0&feature=gp-n-y&google_comment_id=z13exhxj4sfdeffpq04ccbdzhkrnjtwzecs won't let me comment but https://www.youtube.com/watch?v=m7wt3F54Oo0 will work fine.
