### ISSUE TITLE
Hard to make out some of the website buttons

### ISSUE THREAD

**Issue by Nicholas-Steel** [nicu03/dark-youtube-theme#31]
- Upload button (top right corner of page, next to Notification Panel button) is hard to make out.
- Comment Like/Dislike buttons are hard to make out.
- Video Like/Dislike buttons are hard to make out (can be remedied with the Youtube Center user script)

Firefox 50.1.0 x86
Windows 10 x64

**Comment by nicu03** [comment]
thanks, as i mentioned on another issue, the fix will soon be published, the chrome version already works

**Comment by Nicholas-Steel** [comment]
Awesome stuff, thanks.

**Comment by Nicholas-Steel** [comment]
Looks like it just got published.

**Comment by nicu03** [comment]
@Nicholas-Steel Thanks
