### ISSUE TITLE
Live hangout chat window problem

### ISSUE THREAD

**Issue by PaulxxxN** [nicu03/dark-youtube-theme#32]
When viewing a live hangout the chat window to the right has just recently started to display a white background so the comments text becomes invisible also. Google/YouTube appear to have altered something.

**Comment by PaulxxxN** [comment]
Today I discover that the chat window colours have returned to normal - all of yesterday the comment text was black on black for the text boxes and the whole outer background was white. So I'll close this issue, seems it was a temporary blip of unknown origin.

**Comment by nicu03** [comment]
As i have noticed before, youtube usually pushes changes gradually .. maybe that's why the issue disappeared, but it might come back. We'll see, thanks for reporting the bug, i'll keep an eye on it
