### ISSUE TITLE
Live chat on streams white [bug]

### ISSUE THREAD

**Issue by Zahr0** [nicu03/dark-youtube-theme#33]
The chat on livestreams are white instead of black.
![screenshot_1](https://cloud.githubusercontent.com/assets/25164278/22005145/65032d0a-dc37-11e6-8968-5bfbed97ae72.png)

**Comment by nicu03** [comment]
I already made an update for firefox for this bug, and the fix for firefox and opera will be published this week in the store.
@Zahr0 thanks for reporting it
