### ISSUE TITLE
Can't get rid of Dark YouTube theme. Please Help!

### ISSUE THREAD

**Issue by pennywise134** [nicu03/dark-youtube-theme#53]
Hopefully someone can help me, I've tried disabling and removing the dark YouTube add on for my Firefox but it wont go away! Even after uninstalling and re-installing Firefox its still there.

I've attached a screenshot showing that the theme is still active even though it is no longer in the add-ons list. And before you comment, no Classic Theme Restorer is not the problem. I have even tried with a clean install of Firefox and the same problem occurs.

Please help!!

![2017-08-28 21_38_09-add-ons manager](https://user-images.githubusercontent.com/21064443/29800744-be9162f8-8c39-11e7-8087-d73241e9fafb.png)

**Comment by nicu03** [comment]
Hey @pennywise134 ,
youtube has now a built in dark mode,  which you can enable / disable by clicking on your profile icon in the top right, then "dark theme". It's very likely that you are using it.
more details here https://techcrunch.com/2017/05/02/youtube-revamps-its-desktop-site-with-an-updated-design-optional-dark-theme-and-faster-framework/

I'm sorry you had to reinstall firefox.

**Comment by pennywise134** [comment]
@nicu03 I am familiar with YouTube's new dark mode, and I can assure you it is NOT being used here. Please assist me as your add on has broken my browser.

**Comment by nicu03** [comment]
try a private browsing window with no addons, not logged in to youtube. My addon is compliant with the latest firefox technologies and doesn't break browsers, computers or anything like that :smile:

**Comment by pennywise134** [comment]
@nicu03 okay that did work, but when I am not using a private window I'm unable to click the profile icon to sign out of YouTube. This only started happening when I installed your add-on, so I don;t see how it could not be related...

**Comment by nicu03** [comment]
try to disable all addons, clear your cookies (just for youtube), sign in again and see if it works.
afterwards, enable your addons . 
I hope everything should be fine

**Comment by pennywise134** [comment]
clearing cookies worked, thank you
