### ISSUE TITLE
Youtube has new interface

### ISSUE THREAD

**Issue by lloricode** [nicu03/dark-youtube-theme#54]
the theme now was not affect :|

**Comment by nicu03** [comment]
with the last update, 4.1, it should support the new youtube layout also

**Comment by lloricode** [comment]
on watching a video, only comment is dark,

**Comment by KingNut** [comment]
Youtube looks like this atm:

[URL=http://www.bilder-upload.eu/show.php?file=c94aab-1504191911.png][IMG]http://www.bilder-upload.eu/thumb/c94aab-1504191911.png[/IMG][/URL]

[URL=http://www.bilder-upload.eu/show.php?file=8500d8-1504192267.png][IMG]http://www.bilder-upload.eu/thumb/8500d8-1504192267.png[/IMG][/URL]

[URL=http://www.bilder-upload.eu/show.php?file=4d1ea9-1504192281.png][IMG]http://www.bilder-upload.eu/thumb/4d1ea9-1504192281.png[/IMG][/URL]

[URL=http://www.bilder-upload.eu/show.php?file=6d6e96-1504192296.png][IMG]http://www.bilder-upload.eu/thumb/6d6e96-1504192296.png[/IMG][/URL]

**Comment by lloricode** [comment]
@KingNut , yes that is exactly, but i expected that majority is dark , :|

**Comment by KingNut** [comment]
Yes, the old youtube layout was complete dark and the letters white/grey.

**Comment by lloricode** [comment]
Wow! Thanks you @KingNut  :100:
